/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProtecaoRouteImport } from './routes/protecao'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StatusRouteImport } from './routes/status'
import { Route as VendedoresRouteImport } from './routes/vendedores'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedVerificacaoRouteImport } from './routes/_authenticated/verificacao'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as VendedorSlugRouteImport } from './routes/vendedor.$slug'
import { Route as AuthenticatedCheckoutSlugRouteImport } from './routes/_authenticated/checkout.$slug'
import { Route as AuthenticatedPedidoIdRouteImport } from './routes/_authenticated/pedido.$id'
import { Route as AuthenticatedReciboIdRouteImport } from './routes/_authenticated/recibo.$id'
import { Route as ApiPublicDiditWebhookRouteImport } from './routes/api/public/didit-webhook'
import { Route as ApiPublicEfiWebhookRouteImport } from './routes/api/public/efi-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtecaoRoute = ProtecaoRouteImport.update({
  id: '/protecao',
  path: '/protecao',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedoresRoute = VendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerificacaoRoute =
  AuthenticatedVerificacaoRouteImport.update({
    id: '/verificacao',
    path: '/verificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorSlugRoute = VendedorSlugRouteImport.update({
  id: '/vendedor/$slug',
  path: '/vendedor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutSlugRoute =
  AuthenticatedCheckoutSlugRouteImport.update({
    id: '/checkout/$slug',
    path: '/checkout/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidoIdRoute = AuthenticatedPedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReciboIdRoute = AuthenticatedReciboIdRouteImport.update({
  id: '/recibo/$id',
  path: '/recibo/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDiditWebhookRoute = ApiPublicDiditWebhookRouteImport.update({
  id: '/api/public/didit-webhook',
  path: '/api/public/didit-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEfiWebhookRoute = ApiPublicEfiWebhookRouteImport.update({
  id: '/api/public/efi-webhook',
  path: '/api/public/efi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/produtos': typeof ProdutosRoute
  '/protecao': typeof ProtecaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/vendedores': typeof VendedoresRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/verificacao': typeof AuthenticatedVerificacaoRoute
  '/p/$slug': typeof PSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/vendedor/$slug': typeof VendedorSlugRoute
  '/checkout/$slug': typeof AuthenticatedCheckoutSlugRoute
  '/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/recibo/$id': typeof AuthenticatedReciboIdRoute
  '/api/public/didit-webhook': typeof ApiPublicDiditWebhookRoute
  '/api/public/efi-webhook': typeof ApiPublicEfiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/produtos': typeof ProdutosRoute
  '/protecao': typeof ProtecaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/vendedores': typeof VendedoresRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/verificacao': typeof AuthenticatedVerificacaoRoute
  '/p/$slug': typeof PSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/vendedor/$slug': typeof VendedorSlugRoute
  '/checkout/$slug': typeof AuthenticatedCheckoutSlugRoute
  '/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/recibo/$id': typeof AuthenticatedReciboIdRoute
  '/api/public/didit-webhook': typeof ApiPublicDiditWebhookRoute
  '/api/public/efi-webhook': typeof ApiPublicEfiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/produtos': typeof ProdutosRoute
  '/protecao': typeof ProtecaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/vendedores': typeof VendedoresRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/verificacao': typeof AuthenticatedVerificacaoRoute
  '/p/$slug': typeof PSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/vendedor/$slug': typeof VendedorSlugRoute
  '/_authenticated/checkout/$slug': typeof AuthenticatedCheckoutSlugRoute
  '/_authenticated/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/_authenticated/recibo/$id': typeof AuthenticatedReciboIdRoute
  '/api/public/didit-webhook': typeof ApiPublicDiditWebhookRoute
  '/api/public/efi-webhook': typeof ApiPublicEfiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/produtos'
    | '/protecao'
    | '/reset-password'
    | '/status'
    | '/vendedores'
    | '/admin'
    | '/dashboard'
    | '/favoritos'
    | '/mensagens'
    | '/notificacoes'
    | '/verificacao'
    | '/p/$slug'
    | '/produto/$slug'
    | '/vendedor/$slug'
    | '/checkout/$slug'
    | '/pedido/$id'
    | '/recibo/$id'
    | '/api/public/didit-webhook'
    | '/api/public/efi-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/produtos'
    | '/protecao'
    | '/reset-password'
    | '/status'
    | '/vendedores'
    | '/admin'
    | '/dashboard'
    | '/favoritos'
    | '/mensagens'
    | '/notificacoes'
    | '/verificacao'
    | '/p/$slug'
    | '/produto/$slug'
    | '/vendedor/$slug'
    | '/checkout/$slug'
    | '/pedido/$id'
    | '/recibo/$id'
    | '/api/public/didit-webhook'
    | '/api/public/efi-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/produtos'
    | '/protecao'
    | '/reset-password'
    | '/status'
    | '/vendedores'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/favoritos'
    | '/_authenticated/mensagens'
    | '/_authenticated/notificacoes'
    | '/_authenticated/verificacao'
    | '/p/$slug'
    | '/produto/$slug'
    | '/vendedor/$slug'
    | '/_authenticated/checkout/$slug'
    | '/_authenticated/pedido/$id'
    | '/_authenticated/recibo/$id'
    | '/api/public/didit-webhook'
    | '/api/public/efi-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProdutosRoute: typeof ProdutosRoute
  ProtecaoRoute: typeof ProtecaoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatusRoute: typeof StatusRoute
  VendedoresRoute: typeof VendedoresRoute
  PSlugRoute: typeof PSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  VendedorSlugRoute: typeof VendedorSlugRoute
  ApiPublicDiditWebhookRoute: typeof ApiPublicDiditWebhookRoute
  ApiPublicEfiWebhookRoute: typeof ApiPublicEfiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protecao': {
      id: '/protecao'
      path: '/protecao'
      fullPath: '/protecao'
      preLoaderRoute: typeof ProtecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedores': {
      id: '/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof VendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verificacao': {
      id: '/_authenticated/verificacao'
      path: '/verificacao'
      fullPath: '/verificacao'
      preLoaderRoute: typeof AuthenticatedVerificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor/$slug': {
      id: '/vendedor/$slug'
      path: '/vendedor/$slug'
      fullPath: '/vendedor/$slug'
      preLoaderRoute: typeof VendedorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout/$slug': {
      id: '/_authenticated/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof AuthenticatedCheckoutSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedido/$id': {
      id: '/_authenticated/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof AuthenticatedPedidoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recibo/$id': {
      id: '/_authenticated/recibo/$id'
      path: '/recibo/$id'
      fullPath: '/recibo/$id'
      preLoaderRoute: typeof AuthenticatedReciboIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/didit-webhook': {
      id: '/api/public/didit-webhook'
      path: '/api/public/didit-webhook'
      fullPath: '/api/public/didit-webhook'
      preLoaderRoute: typeof ApiPublicDiditWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/efi-webhook': {
      id: '/api/public/efi-webhook'
      path: '/api/public/efi-webhook'
      fullPath: '/api/public/efi-webhook'
      preLoaderRoute: typeof ApiPublicEfiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedVerificacaoRoute: typeof AuthenticatedVerificacaoRoute
  AuthenticatedCheckoutSlugRoute: typeof AuthenticatedCheckoutSlugRoute
  AuthenticatedPedidoIdRoute: typeof AuthenticatedPedidoIdRoute
  AuthenticatedReciboIdRoute: typeof AuthenticatedReciboIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedVerificacaoRoute: AuthenticatedVerificacaoRoute,
  AuthenticatedCheckoutSlugRoute: AuthenticatedCheckoutSlugRoute,
  AuthenticatedPedidoIdRoute: AuthenticatedPedidoIdRoute,
  AuthenticatedReciboIdRoute: AuthenticatedReciboIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProdutosRoute: ProdutosRoute,
  ProtecaoRoute: ProtecaoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatusRoute: StatusRoute,
  VendedoresRoute: VendedoresRoute,
  PSlugRoute: PSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  VendedorSlugRoute: VendedorSlugRoute,
  ApiPublicDiditWebhookRoute: ApiPublicDiditWebhookRoute,
  ApiPublicEfiWebhookRoute: ApiPublicEfiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
