/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProdutosProibidosRouteImport } from './routes/produtos-proibidos'
import { Route as ProtecaoRouteImport } from './routes/protecao'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TaxasRouteImport } from './routes/taxas'
import { Route as VendedoresRouteImport } from './routes/vendedores'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedVerificacaoRouteImport } from './routes/_authenticated/verificacao'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogEditarRouteImport } from './routes/blog.editar'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as VendedorSlugRouteImport } from './routes/vendedor.$slug'
import { Route as AuthenticatedPedidoIdRouteImport } from './routes/_authenticated/pedido.$id'
import { Route as AuthenticatedReciboIdRouteImport } from './routes/_authenticated/recibo.$id'
import { Route as ApiPublicDiditWebhookRouteImport } from './routes/api/public/didit-webhook'
import { Route as ApiPublicEfiWebhookRouteImport } from './routes/api/public/efi-webhook'
import { Route as ApiPublicRobotsRouteImport } from './routes/api/public/robots'
import { Route as ApiPublicSitemapRouteImport } from './routes/api/public/sitemap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosProibidosRoute = ProdutosProibidosRouteImport.update({
  id: '/produtos-proibidos',
  path: '/produtos-proibidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtecaoRoute = ProtecaoRouteImport.update({
  id: '/protecao',
  path: '/protecao',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxasRoute = TaxasRouteImport.update({
  id: '/taxas',
  path: '/taxas',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedoresRoute = VendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerificacaoRoute =
  AuthenticatedVerificacaoRouteImport.update({
    id: '/verificacao',
    path: '/verificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogEditarRoute = BlogEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => BlogRoute,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorSlugRoute = VendedorSlugRouteImport.update({
  id: '/vendedor/$slug',
  path: '/vendedor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPedidoIdRoute = AuthenticatedPedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReciboIdRoute = AuthenticatedReciboIdRouteImport.update({
  id: '/recibo/$id',
  path: '/recibo/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDiditWebhookRoute = ApiPublicDiditWebhookRouteImport.update({
  id: '/api/public/didit-webhook',
  path: '/api/public/didit-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEfiWebhookRoute = ApiPublicEfiWebhookRouteImport.update({
  id: '/api/public/efi-webhook',
  path: '/api/public/efi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobotsRoute = ApiPublicRobotsRouteImport.update({
  id: '/api/public/robots',
  path: '/api/public/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapRoute = ApiPublicSitemapRouteImport.update({
  id: '/api/public/sitemap',
  path: '/api/public/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/labs': typeof LabsRoute
  '/ofertas': typeof OfertasRoute
  '/produtos': typeof ProdutosRoute
  '/produtos-proibidos': typeof ProdutosProibidosRoute
  '/protecao': typeof ProtecaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/seguranca': typeof SegurancaRoute
  '/status': typeof StatusRoute
  '/taxas': typeof TaxasRoute
  '/vendedores': typeof VendedoresRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/verificacao': typeof AuthenticatedVerificacaoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/editar': typeof BlogEditarRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/vendedor/$slug': typeof VendedorSlugRoute
  '/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/recibo/$id': typeof AuthenticatedReciboIdRoute
  '/api/public/didit-webhook': typeof ApiPublicDiditWebhookRoute
  '/api/public/efi-webhook': typeof ApiPublicEfiWebhookRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/labs': typeof LabsRoute
  '/ofertas': typeof OfertasRoute
  '/produtos': typeof ProdutosRoute
  '/produtos-proibidos': typeof ProdutosProibidosRoute
  '/protecao': typeof ProtecaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/seguranca': typeof SegurancaRoute
  '/status': typeof StatusRoute
  '/taxas': typeof TaxasRoute
  '/vendedores': typeof VendedoresRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/verificacao': typeof AuthenticatedVerificacaoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/editar': typeof BlogEditarRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/vendedor/$slug': typeof VendedorSlugRoute
  '/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/recibo/$id': typeof AuthenticatedReciboIdRoute
  '/api/public/didit-webhook': typeof ApiPublicDiditWebhookRoute
  '/api/public/efi-webhook': typeof ApiPublicEfiWebhookRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/labs': typeof LabsRoute
  '/ofertas': typeof OfertasRoute
  '/produtos': typeof ProdutosRoute
  '/produtos-proibidos': typeof ProdutosProibidosRoute
  '/protecao': typeof ProtecaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/seguranca': typeof SegurancaRoute
  '/status': typeof StatusRoute
  '/taxas': typeof TaxasRoute
  '/vendedores': typeof VendedoresRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/verificacao': typeof AuthenticatedVerificacaoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/editar': typeof BlogEditarRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/vendedor/$slug': typeof VendedorSlugRoute
  '/_authenticated/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/_authenticated/recibo/$id': typeof AuthenticatedReciboIdRoute
  '/api/public/didit-webhook': typeof ApiPublicDiditWebhookRoute
  '/api/public/efi-webhook': typeof ApiPublicEfiWebhookRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/blog'
    | '/como-funciona'
    | '/labs'
    | '/ofertas'
    | '/produtos'
    | '/produtos-proibidos'
    | '/protecao'
    | '/reset-password'
    | '/roadmap'
    | '/seguranca'
    | '/status'
    | '/taxas'
    | '/vendedores'
    | '/admin'
    | '/dashboard'
    | '/favoritos'
    | '/mensagens'
    | '/notificacoes'
    | '/suporte'
    | '/verificacao'
    | '/blog/$slug'
    | '/blog/editar'
    | '/checkout/$slug'
    | '/p/$slug'
    | '/produto/$slug'
    | '/vendedor/$slug'
    | '/pedido/$id'
    | '/recibo/$id'
    | '/api/public/didit-webhook'
    | '/api/public/efi-webhook'
    | '/api/public/robots'
    | '/api/public/sitemap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/blog'
    | '/como-funciona'
    | '/labs'
    | '/ofertas'
    | '/produtos'
    | '/produtos-proibidos'
    | '/protecao'
    | '/reset-password'
    | '/roadmap'
    | '/seguranca'
    | '/status'
    | '/taxas'
    | '/vendedores'
    | '/admin'
    | '/dashboard'
    | '/favoritos'
    | '/mensagens'
    | '/notificacoes'
    | '/suporte'
    | '/verificacao'
    | '/blog/$slug'
    | '/blog/editar'
    | '/checkout/$slug'
    | '/p/$slug'
    | '/produto/$slug'
    | '/vendedor/$slug'
    | '/pedido/$id'
    | '/recibo/$id'
    | '/api/public/didit-webhook'
    | '/api/public/efi-webhook'
    | '/api/public/robots'
    | '/api/public/sitemap'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ajuda'
    | '/auth'
    | '/blog'
    | '/como-funciona'
    | '/labs'
    | '/ofertas'
    | '/produtos'
    | '/produtos-proibidos'
    | '/protecao'
    | '/reset-password'
    | '/roadmap'
    | '/seguranca'
    | '/status'
    | '/taxas'
    | '/vendedores'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/favoritos'
    | '/_authenticated/mensagens'
    | '/_authenticated/notificacoes'
    | '/_authenticated/suporte'
    | '/_authenticated/verificacao'
    | '/blog/$slug'
    | '/blog/editar'
    | '/checkout/$slug'
    | '/p/$slug'
    | '/produto/$slug'
    | '/vendedor/$slug'
    | '/_authenticated/pedido/$id'
    | '/_authenticated/recibo/$id'
    | '/api/public/didit-webhook'
    | '/api/public/efi-webhook'
    | '/api/public/robots'
    | '/api/public/sitemap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  LabsRoute: typeof LabsRoute
  OfertasRoute: typeof OfertasRoute
  ProdutosRoute: typeof ProdutosRoute
  ProdutosProibidosRoute: typeof ProdutosProibidosRoute
  ProtecaoRoute: typeof ProtecaoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  SegurancaRoute: typeof SegurancaRoute
  StatusRoute: typeof StatusRoute
  TaxasRoute: typeof TaxasRoute
  VendedoresRoute: typeof VendedoresRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  PSlugRoute: typeof PSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  VendedorSlugRoute: typeof VendedorSlugRoute
  ApiPublicDiditWebhookRoute: typeof ApiPublicDiditWebhookRoute
  ApiPublicEfiWebhookRoute: typeof ApiPublicEfiWebhookRoute
  ApiPublicRobotsRoute: typeof ApiPublicRobotsRoute
  ApiPublicSitemapRoute: typeof ApiPublicSitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos-proibidos': {
      id: '/produtos-proibidos'
      path: '/produtos-proibidos'
      fullPath: '/produtos-proibidos'
      preLoaderRoute: typeof ProdutosProibidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protecao': {
      id: '/protecao'
      path: '/protecao'
      fullPath: '/protecao'
      preLoaderRoute: typeof ProtecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxas': {
      id: '/taxas'
      path: '/taxas'
      fullPath: '/taxas'
      preLoaderRoute: typeof TaxasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedores': {
      id: '/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof VendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verificacao': {
      id: '/_authenticated/verificacao'
      path: '/verificacao'
      fullPath: '/verificacao'
      preLoaderRoute: typeof AuthenticatedVerificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/editar': {
      id: '/blog/editar'
      path: '/editar'
      fullPath: '/blog/editar'
      preLoaderRoute: typeof BlogEditarRouteImport
      parentRoute: typeof BlogRoute
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor/$slug': {
      id: '/vendedor/$slug'
      path: '/vendedor/$slug'
      fullPath: '/vendedor/$slug'
      preLoaderRoute: typeof VendedorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pedido/$id': {
      id: '/_authenticated/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof AuthenticatedPedidoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recibo/$id': {
      id: '/_authenticated/recibo/$id'
      path: '/recibo/$id'
      fullPath: '/recibo/$id'
      preLoaderRoute: typeof AuthenticatedReciboIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/didit-webhook': {
      id: '/api/public/didit-webhook'
      path: '/api/public/didit-webhook'
      fullPath: '/api/public/didit-webhook'
      preLoaderRoute: typeof ApiPublicDiditWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/efi-webhook': {
      id: '/api/public/efi-webhook'
      path: '/api/public/efi-webhook'
      fullPath: '/api/public/efi-webhook'
      preLoaderRoute: typeof ApiPublicEfiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robots': {
      id: '/api/public/robots'
      path: '/api/public/robots'
      fullPath: '/api/public/robots'
      preLoaderRoute: typeof ApiPublicRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap': {
      id: '/api/public/sitemap'
      path: '/api/public/sitemap'
      fullPath: '/api/public/sitemap'
      preLoaderRoute: typeof ApiPublicSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedVerificacaoRoute: typeof AuthenticatedVerificacaoRoute
  AuthenticatedPedidoIdRoute: typeof AuthenticatedPedidoIdRoute
  AuthenticatedReciboIdRoute: typeof AuthenticatedReciboIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedVerificacaoRoute: AuthenticatedVerificacaoRoute,
  AuthenticatedPedidoIdRoute: AuthenticatedPedidoIdRoute,
  AuthenticatedReciboIdRoute: AuthenticatedReciboIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogEditarRoute: typeof BlogEditarRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogEditarRoute: BlogEditarRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AjudaRoute: AjudaRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  LabsRoute: LabsRoute,
  OfertasRoute: OfertasRoute,
  ProdutosRoute: ProdutosRoute,
  ProdutosProibidosRoute: ProdutosProibidosRoute,
  ProtecaoRoute: ProtecaoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  SegurancaRoute: SegurancaRoute,
  StatusRoute: StatusRoute,
  TaxasRoute: TaxasRoute,
  VendedoresRoute: VendedoresRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  PSlugRoute: PSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  VendedorSlugRoute: VendedorSlugRoute,
  ApiPublicDiditWebhookRoute: ApiPublicDiditWebhookRoute,
  ApiPublicEfiWebhookRoute: ApiPublicEfiWebhookRoute,
  ApiPublicRobotsRoute: ApiPublicRobotsRoute,
  ApiPublicSitemapRoute: ApiPublicSitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
